accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('signup/student/', student_signup, name='student_s'),
    path('signup/teacher/', teacher_signup, name='teacher_s'),

    path('teacher/<int:pk>/', TeacherProfile.as_view(), name='teacher_p'),
    path('student/<int:pk>/', StudentProfile.as_view(), name='student_p'),

    path('teacher/<int:pk>/update/', TeacherUpdate.as_view(), name='teacher_up'),
    path('student/<int:pk>/update/', StudentUpdate.as_view(), name='student_up'),

    path('students/all/', AllStudent.as_view(), name='all_s'),
    path('teachers/all/', AllTeacher.as_view(), name='all_t'),

    path('teacher/<int:teacher_id>/add/', add_notice, name='add_notice'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/detail/', notice_detail, name='notice_detail'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/question/add/', add_question, name='add_question'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/ques/<int:ques_id>/detail/', ques_detail, name='ques_detail'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/ques/<int:ques_id>/choice/add/', add_choice,
         name='add_choice'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/questionpaper/', ques_paper, name='ques_paper'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/save/', savedata, name='savedata'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/result/', result, name='result'),
]

online_quiz_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Online Quiz System'
admin.site.site_title = 'Admin Login'

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    username = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(max_length=100, unique=True)
    image = models.ImageField(blank=True, null=True)
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []


class Course(models.Model):
    course_name = models.CharField(max_length=100, blank=False, null=False)
    course_code = models.CharField(max_length=10, blank=False, null=False)

    def __str__(self):
        return self.course_name


class Teacher(User, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='teacher')
    courses = models.ManyToManyField(Course, related_name='Course')

    def __str__(self):
        return self.name


years = (('11', '1st Year 1st Semester'), ('12', '1st Year 2nd Semester'),
         ('21', '2nd Year 1st Semester'), ('22', '2nd Year 2nd Semester'),
         ('31', '3rd Year 1st Semester'), ('32', '3rd Year 2nd Semester'),
         ('41', '4th Year 1st Semester'), ('42', '4th Year 2nd Semester'),
         ('51', 'Masters 1st Semester'), ('52', 'Masters 2nd Semester'),)


class Student(User, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='student')
    course_teacher = models.ManyToManyField(Teacher, related_name='Course_Teacher')
    class_roll = models.IntegerField(default=1, blank=False, null=False)
    exam_roll = models.IntegerField(default=123456, blank=False, null=False)
    registration_no = models.IntegerField(default=12345, blank=False, null=False, unique=True)
    batch = models.IntegerField(default=23, blank=False, null=False)
    year = models.CharField(max_length=50, choices=years, default='11')

    def __str__(self):
        return self.name


class Notice(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False, blank=False)
    published_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    start_time = models.DateTimeField(default=timezone.now, null=False, blank=False)
    end_time = models.DateTimeField(default=timezone.now, null=False, blank=False)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title


class Question(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    question_name = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.question_name


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100, null=False, blank=False)
    answer = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Result(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    class_roll = models.IntegerField(default=0)
    exam_roll = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    ac = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    marks = models.IntegerField(default=0)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, DetailView, ListView,UpdateView
from .form import *
from django.contrib.auth import authenticate, login
from django.utils import timezone


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            user = Teacher.objects.get(name=request.user.name)
            return render(request, 'home.html', {'t': user})
        elif request.user.is_student:
            user = Student.objects.get(name=request.user.name)
            return render(request, 'home.html', {'stu': user})
    else:
        return render(request, 'home.html', {})


def teacher_signup(request):
    if request.method == 'POST':
        form = TeacherSignUpForm(request.POST, request.FILES or None)
        if form.is_valid():
            teacher = form.save(commit=False)
            teacher.is_teacher = True
            teacher.save()

            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']

            # authenticate user then login
            user = authenticate(email=email, password=password)
            login(request, user)

            return redirect('home')
        else:
            return render(request,'signup.html', {'form': form})
    else:
        form = TeacherSignUpForm()
        return render(request, 'signup.html', {'form': form})


def student_signup(request):
    if request.method == 'POST':
        form = StudentSignUpForm(request.POST, request.FILES or None)
        if form.is_valid():
            student = form.save(commit=False)
            student.is_student = True
            student.save()

            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']

            # authenticate user then login
            user = authenticate(email=email, password=password)
            login(request, user)
            return redirect('home')
        else:
            return render(request,'signup.html', {'form': form})
    else:
        form = StudentSignUpForm()
        return render(request, 'signup.html', {'form': form})


class AllStudent(ListView):
    model = Student
    template_name = 'accounts/all_student.html'
    context_object_name = 'stu'


class AllTeacher(ListView):
    model = Teacher
    template_name = 'accounts/all_teacher.html'
    context_object_name = 'teacher'


class TeacherProfile(DetailView):
    model = Teacher
    template_name = 'accounts/teacher_profile.html'
    context_object_name = 't'


class StudentProfile(DetailView):
    model = Student
    template_name = 'accounts/student_profile.html'
    context_object_name = 's'


class TeacherUpdate(UpdateView):
    model = Teacher
    fields = ['name','email','image','courses']
    template_name = 'accounts/update.html'
    success_url = reverse_lazy('home')


class StudentUpdate(UpdateView):
    model = Student
    fields = ['name', 'email', 'course_teacher', 'image', 'class_roll', 'exam_roll', 'registration_no', 'batch', 'year']
    template_name = 'accounts/update.html'
    success_url = reverse_lazy('home')


def add_notice(request, teacher_id):
    t = get_object_or_404(Teacher, pk=teacher_id)
    if request.method == "POST":
        form = NoticeForm(request.POST)
        if form.is_valid():
            print("form..")
            notice = form.save(commit=False)
            notice.teacher = t
            notice.save()
            print(notice.start_time)
            #return redirect('home')
            return redirect('home')
    else:
        form = NoticeForm()
        return render(request, 'accounts/add_notice_ques_ch.html', {'form': form})


def notice_detail(request, teacher_id, notice_id):
    n = get_object_or_404(Notice, pk=notice_id)

    for q in n.question_set.all():
        print(q.question_name)
    return render(request, 'accounts/notice_detail.html', {'n': n, 'tid': teacher_id, 'nid': notice_id})


def add_question(request, teacher_id, notice_id):
    n = get_object_or_404(Notice, pk=notice_id)
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            ques = form.save(commit=False)
            ques.notice = n
            ques.save()
            return redirect('accounts:notice_detail', teacher_id, notice_id)
    else:
        form = QuestionForm()
        return render(request, 'accounts/add_notice_ques_ch.html', {'form': form})


def ques_detail(request, teacher_id, notice_id, ques_id):
    q = get_object_or_404(Question, pk=ques_id)
    return render(request, 'accounts/question_detail.html',
                  {'q': q, 'tid': teacher_id, 'nid': notice_id, 'qid': ques_id})


def add_choice(request, teacher_id, notice_id, ques_id):
    q = get_object_or_404(Question, pk=ques_id)
    print('testing..')
    print(q.question_name)
    for c in q.choice_set.all():
        print(c.choice_text)
    if request.method == "POST":
        form = ChoiceForm(request.POST)
        if form.is_valid():
            choice = form.save(commit=False)
            choice.question = q
            choice.save()
            return redirect('accounts:ques_detail', teacher_id, notice_id, ques_id)
    else:
        form = ChoiceForm()
        return render(request, 'accounts/add_notice_ques_ch.html', {'form': form})


def ques_paper(request, teacher_id, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    now = timezone.now()
    end_t = notice.end_time
    start_t = notice.start_time
    delay = []
    pro = []
    over = ''
    processing = ''
    de = ''
    al_exam = ''
    user = Student.objects.get(name=request.user.name)
    for r in notice.result_set.all():
        if r.name == user.name:
            al_exam = "Already Completed Exam"
    if now > end_t:
        over = 'Exam Over'
    elif start_t < now and now < end_t:
        processing = "Exam Processing..."
        pro = [end_t.strftime("%m"), end_t.strftime("%d"), end_t.strftime("%H"), end_t.strftime("%M"),
               end_t.strftime("%S")]
    elif now < start_t:
        de = "Exam Delayed"
        delay = [start_t.strftime("%m"), start_t.strftime("%d"), start_t.strftime("%H"), start_t.strftime("%M"),
                 start_t.strftime("%S")]
        print(start_t)

    context = {
        'notice': notice, 'delay': delay, 'over': over, 'pro': pro, 'p': processing, 'de': de, 'tid':teacher_id,'nid':notice_id,'al':al_exam
    }
    return render(request, 'accounts/question_paper.html', context)


def savedata(request, teacher_id, notice_id):

    notice = get_object_or_404(Notice, pk=notice_id)
    user = Student.objects.get(name=request.user.name)

    aclist = []
    ans = []

    for question in notice.question_set.all():
        name = 'choice' + question.question_name
        if name in request.POST:
            choice = question.choice_set.get(pk=request.POST[name])
            ans.append(choice.id)

        for choice in question.choice_set.all():
            if choice.answer >= 1:
                aclist.append(choice.id)

    print(aclist)
    print(ans)

    ac = len(set(aclist) & set(ans))

    print(ac)

    t = len(aclist)
    r = Result()
    r.notice = notice
    r.name = user.name
    r.class_roll = user.class_roll
    r.exam_roll = user.exam_roll
    r.total = t
    r.ac = ac
    r.wrong = t - ac
    r.marks = ac
    r.save()

    print(r.name)

    return redirect('home')


def result(request, teacher_id, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    r = notice.result_set.all()

    return render(request, 'accounts/result.html', {'res': r})

templates/accounts/add_notice_ques_ch.html
{% extends 'base.html' %}
{% load staticfiles %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}
    <br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7" style="background-color:lavender;">
                <h1>Add</h1><br>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label class="control-label col-sm-2"><b>{{ field.label_tag }}</b></label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="btn btn-outline-success btn-lg" type="submit" style="margin-left: 10%;">Add</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}
{% block messaging %}{% endblock %}

templates/accounts/all_student.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    All Students
{% endblock %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}<br><br>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7">
            <h1>All Students</h1><br>
                <ol>
                {% for s in stu %}
                    <h3><li><a href="{% url 'accounts:student_p' s.id %}"> {{ s.name }}</a></li></h3><br>
                {% endfor %}
                </ol>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>

{% endblock %}
{% block messaging %}{% endblock %}

templates/accounts/all_teacher.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    All Students
{% endblock %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}<br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7">
                <h1>All Teachers</h1><br>
                <ol>
                {% for t in teacher %}
                    <h3><li><a href="{% url 'accounts:teacher_p' t.id %}"> {{ t.name }}</a></li></h3><br>
                {% endfor %}
                </ol>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>

{% endblock %}
{% block messaging %}{% endblock %}

templates/accounts/notice_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    {{ n.title }}
{% endblock %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}<br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7" style="background-color:lavender;"><h1>Published By: {{ n.teacher.name }}</h1><br>
                <h1>Published Date: {{ n.published_date }}</h1><br>
                <h1>Start By: {{ n.start_time }}</h1><br>
                <h1>End By: {{ n.end_time }}</h1><br>

                {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                        <a href="{% url 'accounts:add_question' tid n.id %}"><h3>Add Question</h3></a><br>

                        {% for q in n.question_set.all %}
                            <a href="{% url 'accounts:ques_detail' tid n.id q.id %}"><h3>{{ q.question_name }}</h3></a><br>
                        {% endfor %}
                    {% elif user.is_student %}
                        <h1><a href="{% url 'accounts:ques_paper' tid n.id %}">Start Exam</a></h1><br>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>

{% endblock %}
{% block messaging %}{% endblock %}

templates/accounts/question_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Question
{% endblock %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}<br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7" style="background-color:lavender;">
                <h1>{{ q.notice }}</h1><br>
                <h1>{{ q.question_name }}</h1><br>
                <h1>Add New Choice</h1>
                <a href="{% url 'accounts:add_choice' tid nid q.id %}">Add Choice</a>
                {% for c in q.choice_set.all %}
                    <h3>{{ c.choice_text }}</h3><br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block messaging %}{% endblock %}

templates/accounts/question_paper.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="{% static 'online_quiz_system/img/ju_logo_2.png' %}">
    <link href="{% static 'online_quiz_system/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{{ notice.title }}</title>
    <script type="text/javascript">
        function startTime() {
            var today = new Date();
            var cmo = today.getMonth() + 1;
            var cd = today.getDate();
            var ch = today.getHours();
            var cm = today.getMinutes();
            var cs = today.getSeconds();

            {% if de %}
                document.getElementById('txt').innerHTML = ntime(cmo, cd, ch, cm, cs, {{ delay.0 }}, {{ delay.1 }}, {{ delay.2 }}, {{ delay.3 }}, {{ delay.4 }});
            {% endif %}
            {% if p %}
                document.getElementById('proc').innerHTML = ntime(cmo, cd, ch, cm, cs, {{ pro.0 }}, {{ pro.1 }}, {{ pro.2 }}, {{ pro.3 }}, {{ pro.4 }});
            {% endif %}


            setTimeout(startTime, 100);
        }

        function ntime(cmo, cd, ch, cm, cs, mo, d, h, m, s) {
            var nmo, nd, nh, nm, ns;
            if (s >= cs) {
                ns = s - cs;
            }
            else {
                ns = s - cs + 60;
                cm += 1;
            }
            if (m >= cm) {
                nm = m - cm;
            }
            else {
                nm = m - cm + 60;
                ch += 1;
            }
            if (h >= ch) {
                nh = h - ch;
            }
            else {
                nh = h - ch + 24;
                cd += 1;
            }
            if (d >= cd) {
                nd = d - cd;
            }
            else {
                nd = d - cd + 31;
                cmo += 1;
            }
            if (mo >= cmo) {
                nmo = mo - cmo;
            }
            else {
                nmo = mo - cmo + 12;
            }

            if (nmo <= 0 && nd <= 0 && nh <= 0 && nm <= 0 && ns <= 0) {
                setTimeout(function () {
                    window.location.reload(1);
                });
            }

            return nmo + "Month " + nd + "Day " + nh + "Hours " + nm + "Min " + ns + "s";
        }
    </script>
</head>

<body onload="startTime()">
<header>
    <nav class="navbar navbar-expand-md navbar-dark">
        <img src="{% static 'online_quiz_system/img/ju_logo.png' %}" alt="logo" style="width:40px;">
        <a class="navbar-brand" href="{% url 'home' %}" style="color:#000;">&nbsp;<b></b></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}" style="color:#000;"><b>Home</b> <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:all_t' %}" style="color:#000;"><b>Teachers</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:all_s' %}" style="color:#000;"><b>Students</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:8000/admin/" style="color:#000;"><b>Admin</b></a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {% if user.image %}
                            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
                        {% else %}
                            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}"
                                 width="30"
                                 height="30">
                        {% endif %}
                        &nbsp;<b>{{ user.name }}</b></a>
                        <ul class="dropdown-menu">
                            {% if user.is_teacher %}
                                <li><a href="{% url 'accounts:teacher_p' user.id %}">Profile</a></li>
                            {% elif user.is_student %}
                                <li><a href="{% url 'accounts:student_p' user.id %}">Profile</a></li>
                            {% endif %}

                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="glyphicon glyphicon-user"></span><b>Signup</b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:teacher_s' %}">Teacher</a></li>
                            <li><a href="{% url 'accounts:student_s' %}">Student</a></li>
                        </ul>
                    </li>
                    <li>
                        <span class="glyphicon glyphicon-log-in"></span><a href="{% url 'login' %}"><b>Login</b></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<br><br>
<div class="container">
    <div class="row">
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <div class="col-md-5" style="background-color:lavender;">
            <h3 style="color: blue; margin-left: 10%">{{ notice.title }}</h3>&emsp;<h6
                style="color: blue;margin-left: 10%">Published Date: {{ notice.published_date }}</h6>
            <h4 style="color: green; margin-left: 10%">Exam Start :</h4><h4
                style="color: red;margin-left: 10%"> {{ notice.start_time }}</h4>
            <h4 style="color: green; margin-left: 10%">Exam End :</h4><h4
                style="color: red;margin-left: 10%"> {{ notice.end_time }}</h4><br>
            <p>{{ now }}</p>
        </div>
        <div class="col-md-7" style="background-color:lavender;">
            {% if  de %}
                <h2 style="color: green">{{ de }}</h2>
                <h1 id="txt" style="color: red"></h1>
            {% endif %}
            {% if p %}
                <h2 style="color: green">{{ p }}</h2>
                <h2 style="color: green">Time Remaining</h2>
                <h1 id="proc" style="color: red"></h1>

            {% endif %}
            {% if over %}
                <h2 style="color: green">{{ over }}</h2><br><br>
                <h2><a href="{% url 'accounts:result' tid nid %}">See Result</a></h2>
            {% endif %}

        </div>
    </div>
    <hr>
    <br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {% if notice.document %}
                <img src="{{ notice.document.url }}" width="100%" height="100%"><br>
            {% else %}
                {% if al %}
                    <h1>{{ al }}</h1>
                {% else %}
                    {% if p %}
                        <form action="{% url 'accounts:savedata' tid nid %}" method="post">
                            {% csrf_token %}

                            {% for question in notice.question_set.all %}
                                {{ forloop.counter }}. {{ question.question_name }}<br>
                                {% for choice in question.choice_set.all %}
                                    &nbsp;&nbsp;&nbsp;
                                    <input type="radio" name="choice{{ question.question_name }}"
                                           id="choice{{ forloop.counter }}"
                                           value="{{ choice.id }}">
                                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

                                {% endfor %}
                            {% endfor %}
                            <input type="submit" value="OK">
                        </form>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
<hr>
<br><br>
<!-- FOOTER -->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
</footer>
</main>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'online_quiz_system/js/jquery-3.3.1.min.js' %}"><\/script>')</script>
<script src="{% static 'online_quiz_system/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/accounts/teacher_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block carousel %}{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7">
                {% if t.image %}
                    <img src="{{ t.image.url }}" width="300px" height="300px" alt="img"><br>
                {% else %}
                    <img src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="100px" height="100px"><br>
                {% endif %}
                <h1>Name: {{ t.name }}</h1>
                <h1>Email: {{ t.email }}</h1><br>
                {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                        {% if user.id == t.id %}
                            <a href="{% url 'accounts:add_notice' t.id %}" target="_blank"><h2>Add Notice</h2></a><br>
                            <a href="{% url 'accounts:teacher_up' t.id %}"><h2>Update Your Profile</h2></a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}
{% block messaging %}{% endblock %}