accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('signup/student/', student_signup, name='student_s'),
    path('signup/teacher/', teacher_signup, name='teacher_s'),

    path('teacher/<int:pk>/', TeacherProfile.as_view(), name='teacher_p'),
    path('student/<int:pk>/', StudentProfile.as_view(), name='student_p'),

    path('teacher/<int:pk>/update/', TeacherUpdate.as_view(), name='teacher_up'),
    path('student/<int:pk>/update/', StudentUpdate.as_view(), name='student_up'),

    path('students/all/', AllStudent.as_view(), name='all_s'),
    path('teachers/all/', AllTeacher.as_view(), name='all_t'),

    path('teacher/<int:teacher_id>/add/', add_notice, name='add_notice'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/detail/', notice_detail, name='notice_detail'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/question/add/', add_question, name='add_question'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/ques/<int:ques_id>/detail/', ques_detail, name='ques_detail'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/ques/<int:ques_id>/choice/add/', add_choice,
         name='add_choice'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/questionpaper/', ques_paper, name='ques_paper'),

    path('teacher/<int:teacher_id>/notice/<int:notice_id>/save/', savedata, name='savedata'),
    path('teacher/<int:teacher_id>/notice/<int:notice_id>/result/', result, name='result'),
]

online_quiz_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Online Quiz System'
admin.site.site_title = 'Admin Login'

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    username = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(max_length=100, unique=True)
    image = models.ImageField(blank=True, null=True)
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []


class Course(models.Model):
    course_name = models.CharField(max_length=100, blank=False, null=False)
    course_code = models.CharField(max_length=10, blank=False, null=False)

    def __str__(self):
        return self.course_name


class Teacher(User, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='teacher')
    courses = models.ManyToManyField(Course, related_name='Course')

    def __str__(self):
        return self.name


years = (('11', '1st Year 1st Semester'), ('12', '1st Year 2nd Semester'),
         ('21', '2nd Year 1st Semester'), ('22', '2nd Year 2nd Semester'),
         ('31', '3rd Year 1st Semester'), ('32', '3rd Year 2nd Semester'),
         ('41', '4th Year 1st Semester'), ('42', '4th Year 2nd Semester'),
         ('51', 'Masters 1st Semester'), ('52', 'Masters 2nd Semester'),)


class Student(User, models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='student')
    course_teacher = models.ManyToManyField(Teacher, related_name='Course_Teacher')
    class_roll = models.IntegerField(default=1, blank=False, null=False)
    exam_roll = models.IntegerField(default=123456, blank=False, null=False)
    registration_no = models.IntegerField(default=12345, blank=False, null=False, unique=True)
    batch = models.IntegerField(default=23, blank=False, null=False)
    year = models.CharField(max_length=50, choices=years, default='11')

    def __str__(self):
        return self.name


class Notice(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False, blank=False)
    published_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    start_time = models.DateTimeField(default=timezone.now, null=False, blank=False)
    end_time = models.DateTimeField(default=timezone.now, null=False, blank=False)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title


class Question(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    question_name = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.question_name


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100, null=False, blank=False)
    answer = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Result(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    class_roll = models.IntegerField(default=0)
    exam_roll = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    ac = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    marks = models.IntegerField(default=0)

    def __str__(self):
        return self.name

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'online_quiz_system/img/ju_logo.png' %}">

    <title>{% block title %}Online Quiz System{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'online_quiz_system/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'online_quiz_system/css/carousel.css' %}" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd">
    <a href ="{% url 'home' %}"><img src="{% static 'online_quiz_system/img/ju_logo.png' %}" alt="logo" style="width:40px;"></a>
    <a class="navbar-brand" href="{% url 'home' %}" style="color:#000;">&nbsp;<b></b></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}" style="color:#000;"><b>Home</b> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:all_t' %}" style="color:#000;"><b>Teachers</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:all_s' %}" style="color:#000;"><b>Students</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/" style="color:#000;"><b>Admin</b></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    {% block proimg %}{% endblock %}&nbsp;<b>{{ user.name }}</b></a>
                    <ul class="dropdown-menu">
                        {% if user.is_teacher %}
                            <li><a href="{% url 'accounts:teacher_p' user.id %}">Profile</a></li>
                        {% elif user.is_student %}
                            <li><a href="{% url 'accounts:student_p' user.id %}">Profile</a></li>
                        {% endif %}

                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
            {% else %}
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <span class="glyphicon glyphicon-user"></span><b>Signup</b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'accounts:teacher_s' %}">Teacher</a></li>
                        <li><a href="{% url 'accounts:student_s' %}">Student</a></li>
                    </ul>
                </li>
                <li>
                    <span class="glyphicon glyphicon-log-in"></span><a href="{% url 'login' %}"><b>Login</b></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main">
    {% block carousel %}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="first-slide" src="{% static 'online_quiz_system/img/ju.jpg' %}" alt="First slide">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            {% if not user.is_authenticated %}
                                <h1>Login</h1>
                                <a class="btn btn-lg btn-primary" href="{% url 'login' %}" role="button">Login</a>
                            {% else %}
                                <h1>Logout</h1>
                                <a class="btn btn-lg btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="second-slide" src="{% static 'online_quiz_system/img/ju_nature.jpg' %}"
                         alt="Second slide">
                    <div class="container">
                        <div class="carousel-caption text-right">
                            <h1>See All Teachers</h1>
                            <p><a class="btn btn-lg btn-primary" href="{% url 'accounts:all_t' %}"
                                  role="button">Teachers</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="third-slide" src="{% static 'online_quiz_system/img/ju_shahid_minar.jpg' %}"
                         alt="Third slide">
                    <div class="container">
                        <div class="carousel-caption text-right">
                            <h1>See All Students</h1>
                            <p><a class="btn btn-lg btn-primary" href="{% url 'accounts:all_s' %}"
                                  role="button">Students</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <hr>
    {% endblock %}
    {% block content %}

    {% endblock %}
    {% block messaging %}
        <!-- Marketing messaging and featurettes
        ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

        <div class="container marketing">

            <div class="row">
                <div class="col-lg-4">
                    <img class="rounded-circle"
                         src="{% static 'online_quiz_system/img/ju_logo.png' %}"
                         alt="Generic placeholder image" width="140" height="140">
                    <h2>Jahangirnagar University</h2>
                    <p>Jahangirnagar University accustomed as a residential accessible university in 1970
                        has now 34 departments and Six Faculties along with Two institutes, with added than fifteen
                        thousand
                        students, and about Five hundred academics adherent to teaching and research.</p>
                    <p><a class="btn btn-secondary" href="http://juniv.edu/" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle"
                         src="{% static 'online_quiz_system/img/ju_cse.jpg' %}"
                         alt="Generic placeholder image" width="140" height="140">
                    <h2>Dept of CSE</h2>
                    <p>The study of computer programming itself investigates various aspects of the use of programming
                        languages and complex systems, and human-computer interaction focuses on the challenges in
                        making
                        computers and computations useful, usable, and universally accessible to humans.</p>
                    <p><a class="btn btn-secondary" href="http://www.juniv.edu/department/cse" role="button">View
                        details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle"
                         src="{% static 'online_quiz_system/img/admin.jpg' %}"
                         alt="Generic placeholder image" width="140" height="140">
                    <h2>Admin</h2>
                    <p>The Department of Computer Science and Engineering (CSE), Jahangirnagar University is one of the
                        leading CSE department in Bangladesh. Since its inception in 1991, the Department is playing a
                        vital role in developing skilled ICT professional and researchers.</p>
                    <p><a class="btn btn-secondary" href="http://juniv.edu/department/cse" role="button">View details
                        &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
        </div><!-- /.container -->{% endblock %}

</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'online_quiz_system/js/jquery-3.3.1.min.js' %}"><\/script>')</script>
<script src="{% static 'online_quiz_system/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% if user.is_authenticated %}
    {% block proimg %}
        {% if user.image %}
            <img class="rounded-circle" src="{{ user.image.url }}" width="30" height="30" alt="img">
        {% else %}
            <img class="rounded-circle" src="{% static 'online_quiz_system/img/blank_profile.png' %}" width="30"
                 height="30">
        {% endif %}
    {% endblock %}
{% endif %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_teacher %}
            <ul>
                {% for n in t.notice_set.all %}
                    <li><h2><a href="{% url 'accounts:notice_detail' t.id n.id %}">{{ n.title }}</a></h2>&nbsp;Published
                        Date&nbsp;{{ n.published_date }}</li><br>
                {% endfor %}
            </ul>
        {% elif user.is_student %}
            <ul>
                {% for t in stu.course_teacher.all %}
                    <ul>
                        {% for n in t.notice_set.all %}
                            <li><h2><a href="{% url 'accounts:notice_detail' t.id n.id %}"> {{ n.title }}</a></h2>&emsp;Published
                                By&nbsp;{{ n.teacher }},&nbsp;Published Date&nbsp;{{ n.published_date }}</li><br>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        {% endif %}
        <hr>
    {% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}
    SignUp
{% endblock %}
{% block carousel %}{% endblock %}
<h3>SignUp</h3><br>
{% block content %}
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <section>
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-2"><b>{{ field.label_tag }}</b></label>
                                {{ field }}
                            </div>
                        {% endfor %}
                    </section>
                    <button class="btn btn-outline-success btn-lg" type="submit" style="margin-left: 10%;">SignUp
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block messaging %}{% endblock %}